### ISSUE TITLE
Fluorination workflow no longer working

### ISSUE THREAD

**Issue by adw62** [UCL-CCS/TIES#319]
I tested the fluorination workflow we used in the TIES2.0 paper using the conda version of TIES but can't recreate the data set. I will summaries what I'm seeing here then try and work through a fix:

This is the input and generation script I'm using: [input.zip](https://github.com/UCL-CCS/TIES/files/11304359/input.zip)

It can be run as python flu.py (MDanalysis is needed)

The second ligand H11 fails as follows:

```
Working Directory: /home/a/paris/test_ties20/flu/l_H11
MD Engine: openmm
Trying to open the ligand l_H11.mol2 with ParmEd..
Antechamber: converting to .mol2 and generating charges if necessary
Ligand files already contain charges: False
Ligand files already contain charges: False
Converted /home/a/paris/test_ties20/flu/l_H11.mol2 into .mol2, Log: /home/a/paris/test_ties20/flu/l_H11/mol2/l_H11/antechamber.log
Ligand net charge (-nc): 1
Renaming right molecule (l_H11) atom names are either reused or do not follow the correct format. 
Common atom names: {'C11', 'N2', 'C6', 'H3', 'C16', 'C15', 'C5', 'C9', 'H16', 'C20', 'C25', 'H26', 'C26', 'C19', 'H25', 'C3', 'H29', 'H23', 'H28', 'C2', 'C22', 'C10', 'C14', 'H5', 'H15', 'C17', 'H12', 'H9', 'H8', 'H6', 'H10', 'H20', 'H27', 'H21', 'H7', 'N1', 'H13', 'C8', 'H18', 'O1', 'H17', 'N3', 'H14', 'C18', 'H19', 'H22', 'C13', 'C1', 'C4', 'C24', 'C21', 'C23', 'H4', 'C7', 'C12', 'N4', 'H24'}
Superimposition: optimising the search by narrowing down the starting configuration. 
Superimposition - simple max overlap size: 31
Superimposition of left atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C4, C21, C20, C19, C3, C2]
Superimposition of left atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C7, C6, C5, C10, C9, C8]
Superimposition of left atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C11, C25, C26, C12, C13]
Superimposition of left atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C4, C2, C1]
Superimposition of left atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C16, C15, C24, C23, C17, C22]
Superimposition of right atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C30, C28, C27]
Superimposition of right atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C30, C47, C46, C45, C29, C28]
Superimposition of right atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C37, C51, C52, C38, C39]
Superimposition of right atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C33, C32, C31, C36, C35, C34]
Superimposition of right atoms: Ignoring carbons as starting configurations because they are carbons in a cycle: [C50, C49, C43, C48, C42, C41]
Superimposition: simple max match of atoms after cycle carbons exclusion: 7
Superimposition: initial starting pairs for the search: [(N2, N6), (N4, N8), (O1, O2), (N3, N7), (N1, N5), (C14, C40), (C14, C44), (C18, C40), (C18, C44)]
Using heuristics to select the initial pairs for searching the maximum overlap.Could produce non-optimal results.
Phase 1: The number of SupTops found: 1
SupTops lengths:  57
No dangling hydrogens
Removed earlier general-match general type:H13-H42 with dangling hydrogens: []
No dangling hydrogens
Removed earlier general-match general type:H12-H41 with dangling hydrogens: []
No dangling hydrogens
Removed pairs with charge incompatibility: [((C14, C40), '0.222')]
Accounting for net charge limit of 0.100
Pair removal strategy (q net tol): greedy with disjoint CC removed at each step: True
To meet q net tol: greedy
Checking for disjoint components in the 1 suptops
Removed disjoint components:  []
Internally computed net charge: 1
Initial cumulative charge of the appearing=0.071700, disappearing=0.077699 alchemical regions
Total partial charge in the joint area = -0.075200
Total charge imbalance to be distributed in dis=-0.002499 and app=0.003500
Charge imbalance per atom in dis=-0.000625 and app=0.000875
Final cumulative charge of the appearing=0.075200, disappearing=0.075200 alchemical regions
-------- Summary -----------
Final number of matched pairs: 54 out of 58L/58R
Disappearing atoms: 6.9%
Appearing atoms: 6.9%
Ambertools parmchk2 generating frcmod files for ligands
INFO: frcmod for ligand was computed before. Not repeating.
INFO: frcmod for l_H11 was computed before. Not repeating.
Parmchk2: generate the .frcmod for l_H11.mol2
Parmchk2: created .frcmod: l_H11.frcmod
Joining frcmod files from ligands and checking parmchk2
Aligned C1 id 0 with C27 id 0
Aligned C10 id 9 with C36 id 9
Aligned C11 id 10 with C37 id 10
Aligned C12 id 11 with C38 id 11
Aligned C13 id 12 with C39 id 12
Aligned C15 id 14 with C41 id 14
Aligned C16 id 15 with C42 id 15
Aligned C17 id 16 with C43 id 16
Aligned C18 id 17 with C44 id 17
Aligned C19 id 20 with C45 id 20
Aligned C2 id 1 with C28 id 1
Aligned C20 id 21 with C46 id 21
Aligned C21 id 22 with C47 id 22
Aligned C22 id 25 with C48 id 25
Aligned C23 id 26 with C49 id 26
Aligned C24 id 27 with C50 id 27
Aligned C25 id 29 with C51 id 29
Aligned C26 id 30 with C52 id 30
Aligned C3 id 2 with C29 id 2
Aligned C4 id 3 with C30 id 3
Aligned C5 id 4 with C31 id 4
Aligned C6 id 5 with C32 id 5
Aligned C7 id 6 with C33 id 6
Aligned C8 id 7 with C34 id 7
Aligned C9 id 8 with C35 id 8
Aligned H10 id 32 with H40 id 32
Aligned H14 id 36 with H43 id 36
Aligned H15 id 37 with H44 id 37
Aligned H16 id 57 with H64 id 57
Aligned H17 id 38 with H45 id 38
Aligned H18 id 53 with H60 id 53
Aligned H19 id 51 with H58 id 51
Aligned H20 id 39 with H46 id 39
Aligned H21 id 40 with H47 id 40
Aligned H22 id 41 with H48 id 41
Aligned H23 id 42 with H49 id 42
Aligned H24 id 43 with H50 id 43
Aligned H25 id 44 with H51 id 44
Aligned H26 id 45 with H52 id 45
Aligned H27 id 46 with H53 id 46
Aligned H28 id 56 with H63 id 56
Aligned H29 id 54 with H61 id 54
Aligned H3 id 52 with H59 id 52
Aligned H4 id 47 with H54 id 47
Aligned H5 id 31 with H39 id 31
Aligned H6 id 49 with H56 id 49
Aligned H7 id 50 with H57 id 50
Aligned H8 id 55 with H62 id 55
Aligned H9 id 48 with H55 id 48
Aligned N1 id 18 with N5 id 18
Aligned N2 id 19 with N6 id 19
Aligned N3 id 23 with N7 id 23
Aligned N4 id 28 with N8 id 28
Aligned O1 id 24 with O2 id 24
Create amber7 topology .top
Morph .frcmod after the insertion of dummy angle/dihedrals: OK
Traceback (most recent call last):
  File "/home/a/paris/test_ties20/flu/flu.py", line 63, in <module>
    hybrid.prepare_inputs()
  File "/home/a/ties/m3/envs/paris_t20/lib/python3.9/site-packages/ties/topology_superimposer.py", line 413, in prepare_inputs
    self.morph.merge_frcmod_files(ligcom=dir_ligcom)
  File "/home/a/ties/m3/envs/paris_t20/lib/python3.9/site-packages/ties/pair.py", line 337, in merge_frcmod_files
    shutil.copy(self.frcmod, morph_frcmod)
  File "/home/a/ties/m3/envs/paris_t20/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/a/ties/m3/envs/paris_t20/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/a/paris/test_ties20/flu/l_H11/prep/morph_frcmods/tests/ligand_l_H11/ligand_l_H11_corrected.frcmod'

``` 

Looks like a missing file maybe after trying to add dummy angle/dihedrals? I can see a `ligand_l_H11_corrected.frcmod.uncorrected` file but no `ligand_l_H11_corrected.frcmod`

**Comment by bieniekmateusz** [comment]
Thanks Alex, 

Found it, we are still relaying on the output from tleap which is just text. The ambertools 2020 version uses this:
```
Could not find angle parameter: c3 - cc - c3
```
Whereas the 2022 version uses this:
```
Could not find angle parameter for atom types: c3 - cc - c3
```

I added a patch to the main branch. 

ps. I am moving the CI to mamba. It appears the previous conda based testing started having issues with resolving the environment.

**Comment by bieniekmateusz** [comment]
The commit number e8f9ee0, now added.

**Comment by adw62** [comment]
Nice! thanks for the fix all looks to be working now :)
